STATUS_LIKE = "like"
STATUS_DISLIKE = "dislike"
STATUS_HEART = "heart"

STATUS_CHOICES = [
    (STATUS_LIKE, "Like"),
    (STATUS_DISLIKE, "DisLike"),
    (STATUS_HEART, "Heart"),
]

SERIALIZER_STATUS_CHOICES = [STATUS_LIKE, STATUS_DISLIKE, STATUS_HEART]
